server:
  port: 8080

#Application info
app:
  base:
    url: http://localhost:8080

#cloudinary info
cloudinary:
  cloud-name: dyrg31pym
  api-key: 423542896616712
  api-secret: ZWSisYEHwsqHYKfImdPQqeI-hvo

#Jwt Configuration
jwt:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
  expiration: 604800000

spring:
  application:
    name: ai-resume-analyzer
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #Email Configuration
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 9df840001@smtp-brevo.com
    password: bskT0EJTluYa7dX
    properties:
      mail:
        smtp:
          auth: true
          from: yashsaxena7668@gmail.com
        starttls:
          enable: true
          required: true
    protocol: smtp


  data:
    mongodb:
      uri: mongodb+srv://yash_saxena:Yash%40%2376686@cluster0.9bmzjjg.mongodb.net/ai-resume-analyzer?appName=Cluster0
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}





